name: build-pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: rm-default-runners
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add GitHub to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Install dependencies
      run: uv sync
  build-and-publish-container-image:
    runs-on: rm-default-runners
    env:
      STORAGE_DRIVER: vfs
    container:
      image: nixos/nix
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install buildah
      run: |
        apt-get update
        apt-get install -y ca-certificates buildah openssh-client

    - name: Build Image
      run: |
        nix-develop --command bash -c "
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

          buildah --storage-driver vfs build \
            --isolation chroot \
            --ssh default \
            -t build:latest
            .
          "

    - name: Push image
      run: |
        buildah --version
        buildah login --help
        buildah login -u USERNAME -p {{ screts.GHCR_TOKEN }} ghcr.io
        buildah --storage-driver vfs images
        buildah --storage-driver vfs push \
          localhost/build:latest \
          docker://ghcr.io/relief-melone/playground-python-packaging-importer:latest


