name: build-pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  #build:
  #  runs-on: rm-default-runners
  #  steps:
  #  - name: Checkout Code
  #    uses: actions/checkout@v4
  #  - name: Install uv
  #    uses: astral-sh/setup-uv@v5
  #  - name: setup SSH Agent
  #    uses: webfactory/ssh-agent@v0.9.0
  #    with:
  #      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  #  - name: Add GitHub to known_hosts
  #    run: |
  #      mkdir -p ~/.ssh
  #      ssh-keyscan github.com >> ~/.ssh/known_hosts
  #  - name: Install dependencies
  #    run: uv sync
  #  - name: Set up Docker Buildx
  #    uses: docker/setup-buildx-action@v3
  #    with:
  #      driver-opt: network=host
  #      buildkit-flags: --debug
  #  - name: Docker build
  #    uses: docker/build-push-action@v6
  #    with:
  #      context: .
  #      ssh: |
  #        default=${{ env.SSH_AUTH_SOCK }}
  #      push: false
  kaniko-build:
    runs-on: rm-default-runners
    container:
      image: gcr.io/kaniko-project/executor:debug
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and Push
      run: |
        mkdir .ssh
        echo "{{ secrets.SSH_PRIVATE_KEY }}" > .ssh/id_rsa
        chmod 600 .ssh/id_rsa
        ssh-keyscan github.com >> .ssh/known_hosts

        /kaniko/executor \
          --context "${{ github.workspace }}" \
          --dockerfile "${{ github.workspace }}/Dockerfile" \
          --destination "ghcr.io/relief-melone/playground-python-packaging-importer" \
          --build-arg "SSH_KEY_DIR=.ssh"

