name: build-pipeline

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubnuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install dependencies
      run: uv sync
